version: 0.2
phases:
    pre_build:
        commands:
            - apt-get update -y
            - apt-get install -y software-properties-common 
            - add-apt-repository ppa:git-core/ppa -y
            - apt-get update -y
            - apt-get install -y build-essential python-pip git
            - pip install docker-compose
    build:
        commands:
            - docker-compose up -d