version: 0.2
phases:
    pre_build:
        commands:
            - apt-get update -y
            - apt-get install -y software-properties-common 
            - apt-get update -y
            - pip install docker-compose
    build:
        commands:
            - docker-compose up -d