version: '3.7'

services: 
    web:
        build: ./services/web
        command: python manage.py run -h 0.0.0.0
        volumes:
            - ./services/web/:/usr/src/app
        ports: 
            - 80:80
        env_file: 
            - ./.env.dev
        stdin_open: true
        tty: true